export type EmailAddress = string;
export type DateWithFixedTimezone = Date;
export type Currency = number;
export type MultilineString = string;
export type Integer = number;
export type DateWithoutTime = string;
export type Country = string;
export type State = string;
export type StaffRole = "Manager" | "Developer" | "Architect";

export * from './app-user-to-role.model';
export * from './role.model';
export * from './app-user.model';
export * from './user.model';
export * from './auth0-user.model';
export * from './supplier.model';
export * from './image.model';
export * from './industry.model';
export * from './contact.model';
export * from './staff.model';
export * from './project.model';
export * from './company.model';
